{
  "formatVersion": "1.1",
  "component": {
    "group": "space.vectrix.flare",
    "module": "flare-fastutil",
    "version": "2.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.6"
          }
        },
        {
          "group": "org.checkerframework",
          "module": "checker-qual",
          "version": {
            "requires": "3.18.0"
          }
        }
      ],
      "files": [
        {
          "name": "flare-fastutil-2.0.1.jar",
          "url": "flare-fastutil-2.0.1.jar",
          "size": 98892,
          "sha512": "5a2bc038b826f942ce7067c020c47d89f52100444f3e1004ecdc23ce0b1e87e703aae0acdf8aa9f5fdfc926624567ecdd92d8e9f74de3e254d5be86bfabf8163",
          "sha256": "a44e793c1f9e0b3cdc6084da18fd93083353a600b54b20dc7d6826aec64d041f",
          "sha1": "b07cbd5e37afc030717647781eebe7ba672cdd7a",
          "md5": "98068fce582c806be95ce9eced1f4157"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.6"
          }
        }
      ],
      "files": [
        {
          "name": "flare-fastutil-2.0.1.jar",
          "url": "flare-fastutil-2.0.1.jar",
          "size": 98892,
          "sha512": "5a2bc038b826f942ce7067c020c47d89f52100444f3e1004ecdc23ce0b1e87e703aae0acdf8aa9f5fdfc926624567ecdd92d8e9f74de3e254d5be86bfabf8163",
          "sha256": "a44e793c1f9e0b3cdc6084da18fd93083353a600b54b20dc7d6826aec64d041f",
          "sha1": "b07cbd5e37afc030717647781eebe7ba672cdd7a",
          "md5": "98068fce582c806be95ce9eced1f4157"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flare-fastutil-2.0.1-javadoc.jar",
          "url": "flare-fastutil-2.0.1-javadoc.jar",
          "size": 461427,
          "sha512": "359de8c4d1f1b18ca340c44a154b898b09789ce4e337c401fb763788cbed9c83ac5718cadf0ff8682fd388455732ff948bb925062cb09c457e32cd753648d3bb",
          "sha256": "aecdb46919d635511dc4b6e172f9d89c81268259adc9c173dbbba903422e2c91",
          "sha1": "aa2a67c24848f4a469d4cf6ef39397ecd57c9782",
          "md5": "edfd3d928c6c0c0bc2cf92f044a48192"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flare-fastutil-2.0.1-sources.jar",
          "url": "flare-fastutil-2.0.1-sources.jar",
          "size": 50598,
          "sha512": "7fd69e66e3a0e5d31c9667929b13c5b3114e17abe3cf2304a2f3d8f7185ae4117b122be56b782e6e12853168571532ef2be29252e4fac1f06a36d8847fda781a",
          "sha256": "751e6d64ed57295a698c1af292b838a82b7164fdd610adcec9ee3cb5d4eaf9e5",
          "sha1": "61954dfbe8ae575f48945ad66d80a2c6d1a8fde0",
          "md5": "ef5b8cb101fe06bf079030b83a3f3adf"
        }
      ]
    }
  ]
}
