{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.stephengold",
    "module": "jolt-jni-Linux_ARM64",
    "version": "3.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "jolt-jni-Linux_ARM64-3.5.0.jar",
          "url": "jolt-jni-Linux_ARM64-3.5.0.jar",
          "size": 742212,
          "sha512": "149d55d562c972983034510ebde85c992fb6fe180d82c9465d47a2e2a6902174361555e71c80474b950c180a1124932d2d95f3149e69ae30e94c3beb885b6ab0",
          "sha256": "7edcee5dd0f18fc869d45e84d532b6a408b6342b16bdae36152637d52ba0c4c3",
          "sha1": "d561ecf25212f74dd8e5752fed6607dab5b95de9",
          "md5": "c084ae631470fdc2fb49de705d9b3981"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jolt-jni-Linux_ARM64-3.5.0.jar",
          "url": "jolt-jni-Linux_ARM64-3.5.0.jar",
          "size": 742212,
          "sha512": "149d55d562c972983034510ebde85c992fb6fe180d82c9465d47a2e2a6902174361555e71c80474b950c180a1124932d2d95f3149e69ae30e94c3beb885b6ab0",
          "sha256": "7edcee5dd0f18fc869d45e84d532b6a408b6342b16bdae36152637d52ba0c4c3",
          "sha1": "d561ecf25212f74dd8e5752fed6607dab5b95de9",
          "md5": "c084ae631470fdc2fb49de705d9b3981"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jolt-jni-Linux_ARM64-3.5.0-javadoc.jar",
          "url": "jolt-jni-Linux_ARM64-3.5.0-javadoc.jar",
          "size": 2364066,
          "sha512": "ed951337f32cebf3cf6c46d920c51ea6114edd9cf2aea021c887d51a81a505b4f23997f9a917103570a87e416f9d19e0e5d97a7044f3ba421c62555953e40894",
          "sha256": "773190da00a08935fc68508ceb569a1c337e812de978506dd8a5e546b4f5693e",
          "sha1": "93c87bbf568c4df9c952c0455ef35164e7a39b46",
          "md5": "c1313e319dcdb96f40c07edf42e1ff23"
        }
      ]
    }
  ]
}
