pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        gradlePluginPortal()
        mavenCentral()
    }
}

rootProject.name = 'moud'

def bbModelReaderDir = file('/home/meek/Desktop/DEV/BbModelReader')
if (bbModelReaderDir.exists()) {
    includeBuild(bbModelReaderDir)
}
def fliffelDir = file('/home/meek/Desktop/DEV/fliffel')
if (fliffelDir.exists()) {
    includeBuild(fliffelDir)
}

include 'core'
include 'net'
include 'moud-bootstrap'
include 'client-launcher'
include 'server-minestom'
include 'server-supervisor'
include 'client-fabric'
include 'physics-api'
include 'physics-rapier'
include 'physics-natives'

def editorClientDir = file("editor-client")
if (editorClientDir.exists()) {
    include 'editor-client'
}
