double=Bridge.number({{value}})
Double=Bridge.optionalNumber({{value}})
boolean=Bridge.truthy({{value}})
Boolean=(Boolean) {{value}}
Object={{value}}
Object[]=bridge.all({{value}})
record=Bridge.wrap({{value}}, {{type}}::new)
cast=({{type}}) {{value}}
