{
  "formatVersion": "1.1",
  "component": {
    "group": "gg.moonflower",
    "module": "molang-compiler",
    "version": "3.1.1.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "molang-compiler-3.1.1.19.jar",
          "url": "molang-compiler-3.1.1.19.jar",
          "size": 108463,
          "sha512": "1930160c90eb72cb816c7cff53de8c85389634788428334a1453c88be2db6b919a6489adc0393606b7a30406435e44d98a149856e222926640df35d86ec2e90f",
          "sha256": "08567ae5964242a7cffa93697cd63de60078d8dd375fb89ce426a390a7634100",
          "sha1": "c7c0f9a9d0431c3485a0b6d2a4fb87e3de415ff9",
          "md5": "742b62db0225874bd76881ce68c770ea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.6"
          }
        }
      ],
      "files": [
        {
          "name": "molang-compiler-3.1.1.19.jar",
          "url": "molang-compiler-3.1.1.19.jar",
          "size": 108463,
          "sha512": "1930160c90eb72cb816c7cff53de8c85389634788428334a1453c88be2db6b919a6489adc0393606b7a30406435e44d98a149856e222926640df35d86ec2e90f",
          "sha256": "08567ae5964242a7cffa93697cd63de60078d8dd375fb89ce426a390a7634100",
          "sha1": "c7c0f9a9d0431c3485a0b6d2a4fb87e3de415ff9",
          "md5": "742b62db0225874bd76881ce68c770ea"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "molang-compiler-3.1.1.19-sources.jar",
          "url": "molang-compiler-3.1.1.19-sources.jar",
          "size": 52718,
          "sha512": "f7a87f62363b1b6213457ae0b9f45e1e94593596ef1d47b9cd92235e2e332b3abc7ca2281011f0b380ff20f8802eea714120653196246624a18fb47fa6855531",
          "sha256": "a2522a2db62c0d822c0dd6baf2611b76d1d586178f7c12e53fb19dd847fa700f",
          "sha1": "9db82be5c846326d5abc9bd2790e5e67fa38f2bf",
          "md5": "c1092a31ad1474c8e5011c2263d6c999"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "molang-compiler-3.1.1.19-javadoc.jar",
          "url": "molang-compiler-3.1.1.19-javadoc.jar",
          "size": 375107,
          "sha512": "93aad85702b8f08f5189f4d8107e9e4f87dde212528a04bdec9eefe0da19cfc2f7d4f4ac9a96ceb5667068ad97f97776f04ad15c0cc047a0a8f9c2d809a7158d",
          "sha256": "c61a2189fb91f268ce4048db35d21c4fa49f53f731599d4bb8eadc83a316afc6",
          "sha1": "d7fbba2cd22e239b384b7e2791c8276cc0938aee",
          "md5": "4abf25a1caffb2b2504c2fe37c808fb2"
        }
      ]
    }
  ]
}
