{
  "formatVersion": "1.1",
  "component": {
    "group": "net.minestom",
    "module": "data",
    "version": "1.21-rv3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "data-1.21-rv3.jar",
          "url": "data-1.21-rv3.jar",
          "size": 591497,
          "sha512": "b118f954c09960c2cb2b6c952330ecd4f65d1d6efd802dd82f0c68672ccec3777d751bbb4e0f024f660327a97fbb66d91f2d89de449bda5aa4a734216ab63f7e",
          "sha256": "57af0012d1f207edf98dd2141627c76216ece96d950dcdd12ee8b3e97d2c1a69",
          "sha1": "220064166d554e360a528b2de61c6726a38d028c",
          "md5": "1a31f24a4d04e4eecb49e41e833e69f7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "data-1.21-rv3.jar",
          "url": "data-1.21-rv3.jar",
          "size": 591497,
          "sha512": "b118f954c09960c2cb2b6c952330ecd4f65d1d6efd802dd82f0c68672ccec3777d751bbb4e0f024f660327a97fbb66d91f2d89de449bda5aa4a734216ab63f7e",
          "sha256": "57af0012d1f207edf98dd2141627c76216ece96d950dcdd12ee8b3e97d2c1a69",
          "sha1": "220064166d554e360a528b2de61c6726a38d028c",
          "md5": "1a31f24a4d04e4eecb49e41e833e69f7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "data-1.21-rv3-sources.jar",
          "url": "data-1.21-rv3-sources.jar",
          "size": 591336,
          "sha512": "709d485926d05225b5830a4e7bbcf72966fcb6c49ac1b60b5cd6d5b9ca556a3b75106c4326e86fdb34dda06679ff5bfb4140ae23680e975d31fe4f061ed7031d",
          "sha256": "bdd7290d9a88393def1c28b2e214f9feb1bb12da642e492bf1e1f179c5dcb5e2",
          "sha1": "7c3022d9158b9fdf30cabf491f4cc35fe7829b01",
          "md5": "c93060e6ebc1957bd0b9ebf4a3b19cad"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "data-1.21-rv3-javadoc.jar",
          "url": "data-1.21-rv3-javadoc.jar",
          "size": 91942,
          "sha512": "b69f3ebf9fb9d1c73f65c07990ce2d1aa548525190189a0febc7db09f7ad37fc79b530b0d0d6bad022703749a76c48f0ae4654568da1347d5944d205260c157e",
          "sha256": "2b98781de69ba579a7a4a9474f48e2513b326cfc39aa61f38a0b36534cdf1633",
          "sha1": "826a4f367671109759160884e74f0a31884c1043",
          "md5": "880414ce6bf1ca69586b4fad6e0e02bb"
        }
      ]
    }
  ]
}
