{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.spair",
    "module": "imgui-java-binding",
    "version": "1.88.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "imgui-java-binding-1.88.0.jar",
          "url": "imgui-java-binding-1.88.0.jar",
          "size": 277039,
          "sha512": "ec9489fe87435f001fa94ff934fcf51403d9d9e35f9af26a0661f35f55c69a948a8f732a126d3557e65588938f2a8fb2e8576bc375e3bfb69b5ecc23e3e71811",
          "sha256": "69b8766c61a1e161a55d2342d59dab8e45b891fe6a38fdd5a7f0d51e00ee9f03",
          "sha1": "250e79a43420ae72dc87439488cccabc3c9eef92",
          "md5": "05d8c317623311b0d3457c986649d1f7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "imgui-java-binding-1.88.0.jar",
          "url": "imgui-java-binding-1.88.0.jar",
          "size": 277039,
          "sha512": "ec9489fe87435f001fa94ff934fcf51403d9d9e35f9af26a0661f35f55c69a948a8f732a126d3557e65588938f2a8fb2e8576bc375e3bfb69b5ecc23e3e71811",
          "sha256": "69b8766c61a1e161a55d2342d59dab8e45b891fe6a38fdd5a7f0d51e00ee9f03",
          "sha1": "250e79a43420ae72dc87439488cccabc3c9eef92",
          "md5": "05d8c317623311b0d3457c986649d1f7"
        }
      ]
    }
  ]
}
