{
  "formatVersion": "1.1",
  "component": {
    "group": "com.miry",
    "module": "miry",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "miry-1.0-SNAPSHOT.jar",
          "url": "miry-1.0-SNAPSHOT.jar",
          "size": 723182,
          "sha512": "3085ff215d872c191a32094d43ced52238985eb68feeb437816c1d14a1255cffa996e9daf131693954c40164be1cfdabeaacc0e26f3325d3f8683d11a41a1478",
          "sha256": "958506d3b6185d49507b2fe807510725991bb3e4df0f6ea0f3bf11806b25a29e",
          "sha1": "9f0189671e92e047a6a49f43d4db0cacd1e36716",
          "md5": "7b4758b43746f7e0258669c93a1c769d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.7"
          }
        }
      ],
      "files": [
        {
          "name": "miry-1.0-SNAPSHOT.jar",
          "url": "miry-1.0-SNAPSHOT.jar",
          "size": 723182,
          "sha512": "3085ff215d872c191a32094d43ced52238985eb68feeb437816c1d14a1255cffa996e9daf131693954c40164be1cfdabeaacc0e26f3325d3f8683d11a41a1478",
          "sha256": "958506d3b6185d49507b2fe807510725991bb3e4df0f6ea0f3bf11806b25a29e",
          "sha1": "9f0189671e92e047a6a49f43d4db0cacd1e36716",
          "md5": "7b4758b43746f7e0258669c93a1c769d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "miry-1.0-SNAPSHOT-sources.jar",
          "url": "miry-1.0-SNAPSHOT-sources.jar",
          "size": 348313,
          "sha512": "d8737e3416cebb6184c602387b63462f1673344e3bb7ff9dfb82f08c5280ebc1858175d84a4405a148a4d4e01b92efe41e2b5c74eaa51cf8706d1eac47779e11",
          "sha256": "fdad427b98fd2f5e1b5204a8f0b7a83e4f6d23001620695867b8619a5d45557e",
          "sha1": "a79eef77489a1b6c7e1553e5730922992b647cee",
          "md5": "3424b505c369528e1b2c52a920d444fe"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "miry-1.0-SNAPSHOT-javadoc.jar",
          "url": "miry-1.0-SNAPSHOT-javadoc.jar",
          "size": 1214887,
          "sha512": "89b70c5ec78a18354500890dab68d07d3f90dc505688e745238657fa2c07c26d0ba4918826424aae2399ccf0021280b756fd63523f4aeccd705cfaa49659fd44",
          "sha256": "079981602fb3faa851d359e4d79bb1f39d00a7153ca953121bd4ecd9e369b706",
          "sha1": "b26c55d707ed11de11f426b9e1c94db8d2ed7fe4",
          "md5": "75e061e0dc3bcf340bd6663738195884"
        }
      ]
    }
  ]
}
