{
  "formatVersion": "1.1",
  "component": {
    "group": "foundry.veil",
    "module": "veil-fabric-1.21.1",
    "version": "2.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "gg.moonflower",
          "module": "molang-compiler",
          "version": {
            "requires": "3.1.1.19"
          }
        },
        {
          "group": "io.github.ocelot",
          "module": "glsl-processor",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "io.github.spair",
          "module": "imgui-java-binding",
          "version": {
            "requires": "1.88.0"
          }
        },
        {
          "group": "io.github.spair",
          "module": "imgui-java-lwjgl3",
          "version": {
            "requires": "1.88.0"
          },
          "excludes": [
            {
              "group": "org.lwjgl",
              "module": "*"
            },
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "veil-fabric-1.21.1-2.5.1.jar",
          "url": "veil-fabric-1.21.1-2.5.1.jar",
          "size": 15186187,
          "sha512": "021a7784efcbfdeb60b4b12434c409a5415e77cc339b3afdeedf064dda5ee926342e1682a8efd3fa4ebdc0c53643cf2b2e9bfadee04673d42da9edc88434cc79",
          "sha256": "c29a7364ff42ef26fa668a6e3a6fbb58a2219ea53f226b255712f0fa101723bf",
          "sha1": "6f2b184cd27d9f0e9ef82c9b55e7a65aabad0266",
          "md5": "becbfac41b53a7ac77e54e934ff52a14"
        }
      ],
      "capabilities": [
        {
          "group": "foundry.veil",
          "name": "veil-fabric-1.21.1",
          "version": "2.5.1"
        },
        {
          "group": "foundry.veil",
          "name": "veil",
          "version": "2.5.1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "24.0.1"
          }
        },
        {
          "group": "gg.moonflower",
          "module": "molang-compiler",
          "version": {
            "requires": "3.1.1.19"
          }
        },
        {
          "group": "io.github.ocelot",
          "module": "glsl-processor",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "io.github.spair",
          "module": "imgui-java-binding",
          "version": {
            "requires": "1.88.0"
          }
        },
        {
          "group": "io.github.spair",
          "module": "imgui-java-lwjgl3",
          "version": {
            "requires": "1.88.0"
          },
          "excludes": [
            {
              "group": "org.lwjgl",
              "module": "*"
            },
            {
              "group": "org.lwjgl.lwjgl",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.github.spair",
          "module": "imgui-java-natives-linux",
          "version": {
            "requires": "1.88.0"
          }
        },
        {
          "group": "io.github.spair",
          "module": "imgui-java-natives-macos",
          "version": {
            "requires": "1.88.0"
          }
        },
        {
          "group": "io.github.spair",
          "module": "imgui-java-natives-windows",
          "version": {
            "requires": "1.88.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.0"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.0+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "veil-fabric-1.21.1-2.5.1.jar",
          "url": "veil-fabric-1.21.1-2.5.1.jar",
          "size": 15186187,
          "sha512": "021a7784efcbfdeb60b4b12434c409a5415e77cc339b3afdeedf064dda5ee926342e1682a8efd3fa4ebdc0c53643cf2b2e9bfadee04673d42da9edc88434cc79",
          "sha256": "c29a7364ff42ef26fa668a6e3a6fbb58a2219ea53f226b255712f0fa101723bf",
          "sha1": "6f2b184cd27d9f0e9ef82c9b55e7a65aabad0266",
          "md5": "becbfac41b53a7ac77e54e934ff52a14"
        }
      ],
      "capabilities": [
        {
          "group": "foundry.veil",
          "name": "veil-fabric-1.21.1",
          "version": "2.5.1"
        },
        {
          "group": "foundry.veil",
          "name": "veil",
          "version": "2.5.1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "veil-fabric-1.21.1-2.5.1-sources.jar",
          "url": "veil-fabric-1.21.1-2.5.1-sources.jar",
          "size": 5132203,
          "sha512": "464fbefd92c26b8f40747abda6ec455589dfec7404f4d8c741894583a7fdbbcccfc917a0dd45d01bb0af99ff9dabd427cb152736655246f7c41723af37c8f44f",
          "sha256": "c85a0c0713a93ed416e59da61437436d4007aaa6d88075d3491f56e69da18125",
          "sha1": "43e8d42002faa4157ab801bcff4e5ef9c89ec5b4",
          "md5": "721263650a93d0c75a48ba790de63089"
        }
      ],
      "capabilities": [
        {
          "group": "foundry.veil",
          "name": "veil-fabric-1.21.1",
          "version": "2.5.1"
        },
        {
          "group": "foundry.veil",
          "name": "veil",
          "version": "2.5.1"
        }
      ]
    }
  ]
}
