mouseMoved=PointerSignal
mouseButton1Down=PointerSignal
mouseButton1Up=PointerSignal
mouseButton2Click=PointerSignal
mouseWheelForward=PointerSignal
mouseWheelBackward=PointerSignal
focused=AnySignal
focusLost=FocusLostSignal
