{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.spair",
    "module": "imgui-java-natives-windows",
    "version": "1.88.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "imgui-java-natives-windows-1.88.0.jar",
          "url": "imgui-java-natives-windows-1.88.0.jar",
          "size": 2380031,
          "sha512": "0519cc59b6981d031fe7fe8cb83b4e6a9fa96daa7dfe8ce80f0e6045b9a1b2d522153ba5b23ed9c69354c7e424e090201de19731b0ed646b3b58d8a7146d3311",
          "sha256": "3ffc77e6a3abde3319b83509311a7ac059acebe626a646d544eb69f091910e2d",
          "sha1": "1450070130918a3123c5c9ea8d62256bc879323b",
          "md5": "31ec168d4ea93795bf932e0aacbf73ee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "imgui-java-natives-windows-1.88.0.jar",
          "url": "imgui-java-natives-windows-1.88.0.jar",
          "size": 2380031,
          "sha512": "0519cc59b6981d031fe7fe8cb83b4e6a9fa96daa7dfe8ce80f0e6045b9a1b2d522153ba5b23ed9c69354c7e424e090201de19731b0ed646b3b58d8a7146d3311",
          "sha256": "3ffc77e6a3abde3319b83509311a7ac059acebe626a646d544eb69f091910e2d",
          "sha1": "1450070130918a3123c5c9ea8d62256bc879323b",
          "md5": "31ec168d4ea93795bf932e0aacbf73ee"
        }
      ]
    }
  ]
}
