dependencies {
    implementation project(':core')
    api "dev.hollowcube:luau:${project.luau_version}"

    api "net.bytebuddy:byte-buddy:1.18.13"
    api "net.bytebuddy:byte-buddy-agent:1.18.13"

    runtimeOnly "dev.hollowcube:luau-natives-linux-x64:${project.luau_version}"
    runtimeOnly "dev.hollowcube:luau-natives-windows-x64:${project.luau_version}"
    runtimeOnly "dev.hollowcube:luau-natives-macos-x64:${project.luau_version}"
    runtimeOnly "dev.hollowcube:luau-natives-macos-arm64:${project.luau_version}"
}

tasks.withType(Test).configureEach {
    jvmArgs '--enable-native-access=ALL-UNNAMED'
    jvmArgs '-XX:+EnableDynamicAgentLoading', '-Djdk.attach.allowAttachSelf=true'
}
