{
  "formatVersion": "1.1",
  "component": {
    "group": "org.junit.jupiter",
    "module": "junit-jupiter-params",
    "version": "5.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.12.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.12.0"
          }
        },
        {
          "group": "org.apiguardian",
          "module": "apiguardian-api",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "junit-jupiter-params-5.12.0.jar",
          "url": "junit-jupiter-params-5.12.0.jar",
          "size": 601717,
          "sha512": "fc96b3f7fce8c86bad32d06ca7da4b53ec1b5ba864cd283feb0dc2ad6576539007984ea6302e69a72616cb7d3eac741f976a4fcf779744777d8d60fa84e016e7",
          "sha256": "a4788fe6e25e7f54a478955cc70a96b21c9aa2bbd9f5b601f14050351d1da37d",
          "sha1": "7c5862776576409afb2d059f9e35b4bd52d98690",
          "md5": "db7a8e1ebd871eef976081f4d5fc9ef1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.12.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "junit-jupiter-params-5.12.0.jar",
          "url": "junit-jupiter-params-5.12.0.jar",
          "size": 601717,
          "sha512": "fc96b3f7fce8c86bad32d06ca7da4b53ec1b5ba864cd283feb0dc2ad6576539007984ea6302e69a72616cb7d3eac741f976a4fcf779744777d8d60fa84e016e7",
          "sha256": "a4788fe6e25e7f54a478955cc70a96b21c9aa2bbd9f5b601f14050351d1da37d",
          "sha1": "7c5862776576409afb2d059f9e35b4bd52d98690",
          "md5": "db7a8e1ebd871eef976081f4d5fc9ef1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-params-5.12.0-javadoc.jar",
          "url": "junit-jupiter-params-5.12.0-javadoc.jar",
          "size": 334784,
          "sha512": "9b0a3a6a760fee4c0c1ef20ebd2122b58675b4f051f3881984b9702793c4fd8cafefa92051f6a0ed6802b1ab99d8878179c63672ae2f2d32f4946f9cf4f60502",
          "sha256": "9aa983f9cbbef598bd7ddec60494b2fbeb2b4c1700c8e18685d591023e966696",
          "sha1": "42b71ae375928a43760ff84e383c55eb346475ad",
          "md5": "20f09ebfedd7617db30367abb0b4017b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-params-5.12.0-sources.jar",
          "url": "junit-jupiter-params-5.12.0-sources.jar",
          "size": 91652,
          "sha512": "ac6ff893964efe382c6f30ddc37b59d4c0dfbe0631862cc0ea00bce9dd9d112ccc861cbbc1fd958f40661969e5a321c130a107973d1e97180942f68ccd09df02",
          "sha256": "e1353aa5fb5205bb9263394b944b567d168bdeb6df56d3d2a6005beadcd37c73",
          "sha1": "73f77dc960d70fcd16937198bfdda1b930bed147",
          "md5": "3e6d79e08e2d9dbf177c1fdce0b8c70e"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-params-5.12.0.jar",
          "url": "junit-jupiter-params-5.12.0.jar",
          "size": 601717,
          "sha512": "fc96b3f7fce8c86bad32d06ca7da4b53ec1b5ba864cd283feb0dc2ad6576539007984ea6302e69a72616cb7d3eac741f976a4fcf779744777d8d60fa84e016e7",
          "sha256": "a4788fe6e25e7f54a478955cc70a96b21c9aa2bbd9f5b601f14050351d1da37d",
          "sha1": "7c5862776576409afb2d059f9e35b4bd52d98690",
          "md5": "db7a8e1ebd871eef976081f4d5fc9ef1"
        }
      ]
    }
  ]
}
