{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.stephengold",
    "module": "jolt-jni-Windows64",
    "version": "3.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "jolt-jni-Windows64-3.5.0.jar",
          "url": "jolt-jni-Windows64-3.5.0.jar",
          "size": 742212,
          "sha512": "39da3f30e62345c0190cfd5c4d0a7c1ab62b239735ae39f11ba871d96c092e0af8721af45bb3d61a74ee84cdb785285fd0fb2274439964c183511b8d785ab896",
          "sha256": "43808635282518f805aa279988502aafbfb14995cfd2d709947ab4b72dbdcf43",
          "sha1": "df94d0b47fe78e508af150757737a5320beda6db",
          "md5": "e28e21bb677d7a122d0d8747f2e96fae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jolt-jni-Windows64-3.5.0.jar",
          "url": "jolt-jni-Windows64-3.5.0.jar",
          "size": 742212,
          "sha512": "39da3f30e62345c0190cfd5c4d0a7c1ab62b239735ae39f11ba871d96c092e0af8721af45bb3d61a74ee84cdb785285fd0fb2274439964c183511b8d785ab896",
          "sha256": "43808635282518f805aa279988502aafbfb14995cfd2d709947ab4b72dbdcf43",
          "sha1": "df94d0b47fe78e508af150757737a5320beda6db",
          "md5": "e28e21bb677d7a122d0d8747f2e96fae"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jolt-jni-Windows64-3.5.0-javadoc.jar",
          "url": "jolt-jni-Windows64-3.5.0-javadoc.jar",
          "size": 2363901,
          "sha512": "baba1c576969e909adde2af431c27edfc450508143c1f1520868f9df15d5aadd93ecde5c748fbfcf158f3b23af5c3f039c33d66f8b16b669d9f8c729480311d2",
          "sha256": "5b8dfbd5c87ffdff96539a0852e7db1b3797ed620d594fd21f1cb8dfb1bbf062",
          "sha1": "127e660edd5e8bad5174b36496b5de1a44eaf78c",
          "md5": "683da6e2b19ade4fbee22ca072b1dc1d"
        }
      ]
    }
  ]
}
