package com.meekdev.moud.script.types;

import com.meekdev.moud.core.clazz.Enums;
import com.meekdev.moud.core.clazz.EventDef;
import com.meekdev.moud.core.clazz.CallbackDef;
import com.meekdev.moud.core.clazz.ClassDef;
import com.meekdev.moud.core.clazz.Classes;
import com.meekdev.moud.core.clazz.ClassRegistry;
import com.meekdev.moud.core.clazz.PropertyDef;
import com.meekdev.moud.core.clazz.PropertyType;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.stream.Collectors;

// the luau definitions a place is edited against, written from the class registry rather than kept
// beside it. a property that is not declared cannot appear here, so the api and what an editor
// believes about it cannot drift (8.7)
public final class Types {

    private static final String DIRECTORY = ".moud";
    private static final String FILE = "types.d.luau";

    private Types() {}

    public static Path write(Path place, ClassRegistry classes) throws IOException {
        Path directory = place.resolve(DIRECTORY);
        Files.createDirectories(directory);
        Path file = directory.resolve(FILE);
        Files.writeString(file, declare(classes));
        return file;
    }

    public static String declare(ClassRegistry classes) {
        StringBuilder out = new StringBuilder(4096);
        out.append("""
                -- generated by moud, do not edit and do not commit
                -- the classes below come from the class registry, so this file cannot describe a
                -- property that does not exist

                declare class Vector3
                    x: number
                    y: number
                    z: number
                    magnitude: number
                    unit: Vector3
                    function __add(self, other: Vector3): Vector3
                    function __sub(self, other: Vector3): Vector3
                    function __mul(self, scale: number): Vector3
                    function __unm(self): Vector3
                    function distance(self, other: Vector3): number
                    function distanceSq(self, other: Vector3): number
                    function dot(self, other: Vector3): number
                    function cross(self, other: Vector3): Vector3
                    function lerp(self, other: Vector3, t: number): Vector3
                    function angleTo(self, other: Vector3): number
                    function flat(self): Vector3
                    function clampMagnitude(self, max: number): Vector3
                    function abs(self): Vector3
                    function floor(self): Vector3
                end

                declare class UDim2
                    xScale: number
                    xOffset: number
                    yScale: number
                    yOffset: number
                    function __add(self, other: UDim2): UDim2
                    function __sub(self, other: UDim2): UDim2
                end

                declare class Color
                    r: number
                    g: number
                    b: number
                    a: number
                end

                declare class Quat
                    x: number
                    y: number
                    z: number
                    w: number
                    function slerp(self, other: Quat, t: number): Quat
                    function inverse(self): Quat
                    function rotate(self, v: Vector3): Vector3
                    function mul(self, other: Quat): Quat
                end

                declare class CFrame
                    position: Vector3
                    rotation: Quat
                    lookVector: Vector3
                    rightVector: Vector3
                    upVector: Vector3
                    function __mul(self, other: CFrame): CFrame
                    function inverse(self): CFrame
                    function lerp(self, other: CFrame, t: number): CFrame
                    function toObjectSpace(self, other: CFrame): CFrame
                    function toWorldSpace(self, other: CFrame): CFrame
                    function pointToObjectSpace(self, point: Vector3): Vector3
                    function pointToWorldSpace(self, point: Vector3): Vector3
                    function vectorToObjectSpace(self, v: Vector3): Vector3
                    function vectorToWorldSpace(self, v: Vector3): Vector3
                    function lookAt(self, target: Vector3): CFrame
                end

                declare class Connection
                    function disconnect(self): ()
                end

                declare class ChangedSignal
                    function connect(self, handler: (property: string) -> ()): Connection
                    function once(self, handler: (...any) -> ()): Connection
                    function wait(self, timeout: number?): ...any
                    function every(self, n: number, handler: (...any) -> ()): Connection
                end

                declare class InstanceSignal
                    function connect(self, handler: (instance: Instance) -> ()): Connection
                    function once(self, handler: (...any) -> ()): Connection
                    function wait(self, timeout: number?): ...any
                    function every(self, n: number, handler: (...any) -> ()): Connection
                end

                declare class StepSignal
                    function connect(self, handler: (delta: number) -> ()): Connection
                    function once(self, handler: (...any) -> ()): Connection
                    function wait(self, timeout: number?): ...any
                    function every(self, n: number, handler: (...any) -> ()): Connection
                end

                declare class ReloadedSignal
                    function connect(self, handler: () -> ()): Connection
                    function once(self, handler: (...any) -> ()): Connection
                    function wait(self, timeout: number?): ...any
                    function every(self, n: number, handler: (...any) -> ()): Connection
                end

                declare class PlayerSignal
                    function connect(self, handler: (player: Player) -> ()): Connection
                    function once(self, handler: (...any) -> ()): Connection
                    function wait(self, timeout: number?): ...any
                    function every(self, n: number, handler: (...any) -> ()): Connection
                end

                declare class Player
                    name: string
                    character: Instance?
                    function spawn(self, position: Vector3): ()
                    function ping(self): number
                    function viewTime(self): number
                end

                declare class Players
                    joined: PlayerSignal
                    leaving: PlayerSignal
                    function me(self): Instance?
                    function all(self): { Instance }
                    function near(self, position: Vector3, radius: number, except: Instance?): { Instance }
                    function nearest(self, position: Vector3, radius: number?, except: Instance?): (Instance?, number?)
                    function bodyOf(self, player: string): Instance?
                    function count(self): number
                    function inBox(self, frame: CFrame, size: Vector3, except: Instance?): { Instance }
                    function inPart(self, part: Instance, except: Instance?): { Instance }
                    function inCone(self, position: Vector3, direction: Vector3, angle: number, range: number, except: Instance?): { Instance }
                    function visibleFrom(self, position: Vector3, range: number, except: Instance?): { Instance }
                    function withTag(self, tag: string): { Instance }
                    function random(self, except: Instance?): Instance?
                    function sortedByDistance(self, position: Vector3): { Instance }
                    function inRange(self, a: Instance, b: Instance, range: number): boolean
                    function fromName(self, name: string): Instance?
                end

                """);

        out.append("""
                type TweenInfo = { time: number?, easing: string?, direction: string?, repeats: number?,
                    reverses: boolean?, delay: number? }

                declare class Tween
                    completed: StepSignal
                    function pause(self): ()
                    function resume(self): ()
                    function cancel(self): ()
                    function state(self): string
                end

                type RayHit = { part: Instance, position: Vector3, distance: number, normal: Vector3 }
                type QueryOptions = { exclude: { Instance }?, include: { Instance }?, respectCollides: boolean?, collisionGroup: string?, tag: string?, className: string?, limit: number?, sorted: boolean?,
                    ignoreBlocks: boolean? }

                declare class Instance
                    name: string
                    className: string
                    parent: Instance?
                    changed: ChangedSignal
                    childAdded: InstanceSignal
                    destroying: InstanceSignal
                    function add(self, className: string, properties: { [string]: any }?): Instance
                    function addAll(self, className: string, properties: { { [string]: any } }): number
                    function children(self): { Instance }
                    function find(self, name: string): Instance?
                    function isA(self, className: string): boolean
                    function raycast(self, from: Vector3, direction: Vector3, range: number?, options: QueryOptions?): (Instance?, Vector3?, number?, Vector3?, string?)
                    function spherecast(self, from: Vector3, radius: number, direction: Vector3, range: number?, options: QueryOptions?): (Instance?, Vector3?, number?, Vector3?)
                    function blockcast(self, frame: CFrame, size: Vector3, direction: Vector3, range: number?, options: QueryOptions?): (Instance?, Vector3?, number?, Vector3?)
                    function partsInBox(self, frame: CFrame, size: Vector3, options: QueryOptions?): { Instance }
                    function partsInRadius(self, position: Vector3, radius: number, options: QueryOptions?): { Instance }
                    function partsInPart(self, part: Instance, options: QueryOptions?): { Instance }
                    function raycastAll(self, from: Vector3, direction: Vector3, range: number?, options: QueryOptions?): { RayHit }
                    function raycastMany(self, rays: { { any } }, options: QueryOptions?): { RayHit | false }
                    function nearestPart(self, position: Vector3, radius: number, options: QueryOptions?): (Instance?, number?)
                    function nearestTagged(self, position: Vector3, tag: string, radius: number?): (Instance?, number?)
                    function partsAlongRay(self, from: Vector3, direction: Vector3, range: number?, options: QueryOptions?): { RayHit }
                    function capsulecast(self, from: Vector3, to: Vector3, radius: number, options: QueryOptions?): (Instance?, Vector3?, number?, Vector3?)
                    function sweep(self, part: Instance, direction: Vector3, distance: number, options: QueryOptions?): (Instance?, Vector3?, number?, Vector3?)
                    function partsAtPoint(self, position: Vector3, options: QueryOptions?): { Instance }
                    function boundsOf(self, instances: { Instance }): (CFrame?, Vector3?)
                    function groundAt(self, x: number, z: number, from: number?, options: QueryOptions?): (number?, Vector3?)
                    function surfaceNormal(self, position: Vector3, options: QueryOptions?): Vector3?
                    function heightmap(self, from: Vector3, to: Vector3, step: number?, options: QueryOptions?): { { number } }
                    function findFreeSpot(self, near: Vector3, size: Vector3, radius: number?): Vector3?
                    function findFirstDescendant(self, name: string): Instance?
                    function descendants(self, className: string?): { Instance }
                    function childrenOfClass(self, className: string): { Instance }
                    function firstAncestorOfClass(self, className: string): Instance?
                    function firstAncestor(self, name: string): Instance?
                    function isDescendantOf(self, other: Instance): boolean
                    function byTag(self, tag: string): { Instance }
                    function values(self): { [string]: any }
                    function clone(self, parent: Instance?): Instance?
                    function query(self, selector: string): { Instance }
                    function queryFirst(self, selector: string): Instance?
                    function waitForChild(self, name: string, timeout: number?): Instance?
                    function onChild(self, name: string, fn: (child: Instance) -> ()): Connection
                    function destroy(self): ()
                    function setOwner(self, to: Instance?): ()
                    function addTag(self, tag: string): ()
                    function removeTag(self, tag: string): ()
                    function hasTag(self, tag: string): boolean
                    function getTags(self): { string }
                    function tween(self, goals: { [string]: any }, info: TweenInfo?): Tween
                    function fireServer(self, ...: any): ()
                    function fireClient(self, to: Instance, ...: any): ()
                    function fireAllClients(self, ...: any): ()
                end

                """);

        for (ClassDef<?> def : classes.all()) {
            out.append(clazz(def));
        }

        out.append("""
                declare class Blocks
                    function get(self, at: Vector3): string
                    function set(self, at: Vector3, block: string): ()
                    function fill(self, from: Vector3, to: Vector3, block: string): number
                    function raycast(self, from: Vector3, direction: Vector3, range: number?, options: { fluids: boolean? }?): (string?, Vector3?, number?, Vector3?)
                    function isSolid(self, at: Vector3): boolean
                    function isAir(self, at: Vector3): boolean
                    function isFluid(self, at: Vector3): boolean
                    function lightAt(self, at: Vector3): number
                    function topAt(self, x: number, z: number): number
                    function find(self, block: string, centre: Vector3, radius: number, limit: number?): { Vector3 }
                    function count(self, block: string, from: Vector3, to: Vector3): number
                    function replace(self, from: string, to: string, a: Vector3, b: Vector3): number
                    function sphere(self, centre: Vector3, radius: number, block: string, hollow: boolean?): number
                    function cylinder(self, base: Vector3, radius: number, height: number, block: string, hollow: boolean?): number
                    function line(self, from: Vector3, to: Vector3, block: string): number
                    function hollowBox(self, from: Vector3, to: Vector3, block: string): number
                    function copy(self, from: Vector3, to: Vector3): BlockCopy
                    function paste(self, copy: BlockCopy, at: Vector3, quarterTurns: number?, skipAir: boolean?): number
                    changed: BlockChangedSignal
                end

                type BlockCopy = { size: Vector3, palette: { string }, blocks: { number } }

                declare class BlockChangedSignal
                    function connect(self, handler: (at: Vector3, block: string) -> ()): Connection
                    function once(self, handler: (...any) -> ()): Connection
                    function wait(self, timeout: number?): ...any
                    function every(self, n: number, handler: (...any) -> ()): Connection
                end

                declare class Tags
                    function tagged(self, tag: string): { Instance }
                    function added(self, tag: string): InstanceSignal
                    function removed(self, tag: string): InstanceSignal
                end

                declare class ChatCommandSignal
                    function connect(self, handler: (body: Instance?, text: string, args: { string }) -> ()): Connection
                    function once(self, handler: (...any) -> ()): Connection
                    function wait(self, timeout: number?): ...any
                    function every(self, n: number, handler: (...any) -> ()): Connection
                end

                type ChatMessage = { id: number, text: string, prefix: string, metadata: string, channel: Instance?, source: Instance?, body: Instance?, position: Vector3?, timestamp: number, status: string, [string]: any }
                type ChatCheck = (message: ChatMessage, source: Instance) -> boolean

                declare class ChatMessageSignal
                    function connect(self, handler: (message: ChatMessage) -> ()): Connection
                    function once(self, handler: (...any) -> ()): Connection
                    function wait(self, timeout: number?): ...any
                    function every(self, n: number, handler: (...any) -> ()): Connection
                end

                declare class ChatAnySignal
                    function connect(self, handler: (...any) -> ()): Connection
                    function once(self, handler: (...any) -> ()): Connection
                    function wait(self, timeout: number?): ...any
                    function every(self, n: number, handler: (...any) -> ()): Connection
                end

                declare class Chat
                    function send(self, channelOrText: Instance | string, textOrOptions: (string | { [string]: any })?, options: { [string]: any }?): number
                    function system(self, text: string, options: { [string]: any }?): number
                    function edit(self, id: number, changes: string | { [string]: any }): ()
                    function delete(self, id: number): ()
                    function addPlayer(self, channel: Instance, body: Instance): ()
                    function removePlayer(self, channel: Instance, body: Instance): ()
                    function open(self, prefill: string?): ()
                    function close(self): ()
                    function isOpen(self): boolean
                    function clear(self): ()
                    function setTarget(self, channel: Instance?): ()
                    function getTarget(self): Instance?
                    function messages(self): { ChatMessage }
                    function bubble(self, target: Instance, text: string, look: { [string]: any }?): ()
                    onBubble: ((message: ChatMessage) -> (boolean | { [string]: any })?)?
                    function escape(text: string): string
                    function plain(text: string): string
                    function bodyLink(body: Instance, label: string?): string
                    function itemLink(id: string, count: number?): string
                    function within(range: number): ChatCheck
                    function all(...: ChatCheck): ChatCheck
                    function any(...: ChatCheck): ChatCheck
                    function distance(message: ChatMessage, source: Instance): number?
                    function audible(range: number): ChatCheck
                    function sameTag(tag: string): ChatCheck
                    onIncoming: ((message: ChatMessage) -> { [string]: any }?)?
                    shouldSend: ((message: ChatMessage) -> boolean?)?
                    messageReceived: ChatMessageSignal
                    sending: ChatMessageSignal
                    edited: ChatMessageSignal
                    deleted: ChatAnySignal
                    linkClicked: ChatAnySignal
                    bodyClicked: ChatAnySignal
                    messageClicked: ChatMessageSignal
                    opened: ChatAnySignal
                    closed: ChatAnySignal
                    typing: ChatAnySignal
                end

                declare class History
                    function now(self): number
                    function viewTime(self, body: Instance): number
                    function rewind<T...>(self, time: number, query: () -> T...): T...
                end

                declare class ProximityWatcher
                    entered: ChatAnySignal
                    left: ChatAnySignal
                    near: boolean
                    function stop(self): ()
                end

                declare class Proximity
                    function closestInteractable(self, body: Instance): (Instance?, number?)
                    function watch(self, a: Instance, b: Instance, range: number): ProximityWatcher
                    function falloff(distance: number, min: number, max: number, rolloff: number?): number
                end

                type PathOptions = { maxNodes: number?, maxDrop: number?, height: number? }

                declare class Path
                    function find(self, from: Vector3, to: Vector3, options: PathOptions?): { Vector3 }?
                    function isReachable(self, from: Vector3, to: Vector3, options: PathOptions?): boolean
                    function randomPointNear(self, point: Vector3, radius: number, options: PathOptions?): Vector3?
                end

                declare class Debug
                    function drawLine(self, from: Vector3, to: Vector3, color: Color?, seconds: number?): ()
                    function drawRay(self, from: Vector3, direction: Vector3, color: Color?, seconds: number?): ()
                    function drawBox(self, frame: CFrame, size: Vector3, color: Color?, seconds: number?): ()
                    function drawSphere(self, centre: Vector3, radius: number, color: Color?, seconds: number?): ()
                    function drawPoint(self, at: Vector3, color: Color?, seconds: number?): ()
                    function label(self, at: Vector3, text: string, color: Color?, seconds: number?): ()
                    function watch(self, name: string, value: any): ()
                    function clear(self): ()
                    function queryStats(self): { queries: number, partsTested: number }
                    function profile(self): { [string]: { milliseconds: number, calls: number, worst: number } }
                end

                declare class Zones
                    function at(self, position: Vector3): { Instance }
                end

                declare class Game
                    world: Instance
                    zones: Zones
                    proximity: Proximity
                    path: Path
                    debug: Debug
                    history: History
                    players: Players
                    tags: Tags
                    chat: Chat
                    blocks: Blocks
                    stepped: StepSignal
                    renderStepped: StepSignal
                    reloaded: ReloadedSignal
                    persist: { [string]: any }
                end

                declare class Input
                    mouseX: number
                    mouseY: number
                    mouseDeltaX: number
                    mouseDeltaY: number
                    screenWidth: number
                    screenHeight: number
                    mouseLocked: boolean
                    sensitivity: number
                    function down(self, action: string): boolean
                    function lockMouse(self): ()
                    function releaseMouse(self): ()
                end

                declare game: Game

                declare camera: Camera
                declare input: Input

                declare class Voice
                    function stop(self): ()
                    function setVolume(self, volume: number): ()
                    function setPitch(self, pitch: number): ()
                    function fade(self, volume: number, seconds: number): ()
                    function fadeOut(self, seconds: number): ()
                    function setPosition(self, at: Vector3): ()
                    function isPlaying(self): boolean
                end

                declare class Music
                    function setState(self, name: string, seconds: number?): ()
                    function transitionTo(self, name: string, seconds: number?, quantize: string?): ()
                    function setLayer(self, layer: number, volume: number): ()
                    function blend(self, intensity: number): ()
                    function stop(self, seconds: number?): ()
                end

                type PlayOptions = { volume: number?, pitch: number?, looped: boolean?, bus: string?,
                    priority: number?, at: Vector3?, minDistance: number?, maxDistance: number?,
                    rollOff: number?, fadeIn: number?, stream: boolean? }

                declare audio: {
                    play: (soundId: string, options: PlayOptions?) -> Voice?,
                    playEvent: (name: string, at: Vector3?) -> Voice?,
                    stinger: (name: string, quantize: string?) -> Voice?,
                    defineEvent: (name: string, event: { sounds: { string }, bus: string?, volume: any?,
                        pitch: any?, looped: boolean? }) -> (),
                    tempo: (bpm: number, beatsPerBar: number?) -> (),
                    stopTempo: () -> (),
                    beats: () -> number,
                    beat: StepSignal,
                    bar: StepSignal,
                    setParameter: (name: string, value: number) -> (),
                    getParameter: (name: string) -> number,
                    bindBusVolume: (parameter: string, bus: string, curve: { { number } }) -> (),
                    setSwitch: (group: string, value: string) -> (),
                    getSwitch: (group: string) -> string?,
                    lfo: (parameter: string, shape: string, hertz: number, min: number, max: number) -> (),
                    snapshot: (volumes: { [string]: number }, seconds: number?) -> (),
                    clearSnapshot: (seconds: number?) -> (),
                    sidechain: (sourceBus: string, targetBus: string, amount: number) -> (),
                    reverb: (decaySeconds: number, wet: number) -> (),
                    hrtf: (enabled: boolean) -> (),
                    occlusion: (enabled: boolean) -> (),
                    music: (music: { layers: { string }, states: { [string]: { number } }?, bus: string? }) -> Music,
                    voiceChat: (settings: { enabled: boolean?, strength: number?, filters: { any }? }) -> (),
                    voiceCount: () -> number,
                }

                declare function require(path: string): any
                declare script: Instance

                declare class StoreSession
                    data: { [string]: any }
                    function save(self): ()
                    function release(self): ()
                end

                declare class Store
                    function get(self, key: any): any
                    function set(self, key: any, value: any): ()
                    function remove(self, key: any): ()
                    function update(self, key: any, change: (old: any) -> any): any
                    function keys(self, prefix: string?, limit: number?): { string }
                    function session(self, key: any): StoreSession
                end

                declare function store(name: string): Store
                declare scene: {
                    load: (path: string, parent: Instance?) -> { Instance },
                    save: (instances: any, path: string) -> (),
                    encode: (instances: any) -> string,
                    decode: (text: string, parent: Instance?) -> { Instance },
                }
                declare function clock(): number

                declare cooldown: {
                    ready: (self: any, key: any, name: string, seconds: number) -> boolean,
                    remaining: (self: any, key: any, name: string) -> number,
                    reset: (self: any, key: any, name: string) -> (),
                }

                declare quat: {
                    identity: Quat,
                    axisAngle: (axis: Vector3, radians: number) -> Quat,
                    euler: (x: number, y: number, z: number) -> Quat,
                    lookAt: (forward: Vector3, up: Vector3?) -> Quat,
                    fromTo: (from: Vector3, to: Vector3) -> Quat,
                }

                declare angle: {
                    wrap: (a: number) -> number,
                    delta: (a: number, b: number) -> number,
                    lerp: (a: number, b: number, t: number) -> number,
                }

                declare random: {
                    range: (min: number, max: number) -> number,
                    int: (min: number, max: number) -> number,
                    chance: (probability: number) -> boolean,
                    pick: <T>(list: { T }) -> T?,
                    shuffle: <T>(list: { T }) -> { T },
                    unit: () -> Vector3,
                    onSphere: (radius: number) -> Vector3,
                    inSphere: (radius: number) -> Vector3,
                    inCircle: (radius: number) -> Vector3,
                    inBox: (size: Vector3) -> Vector3,
                }

                declare function vec3(x: number, y: number, z: number): Vector3
                declare function color(r: number, g: number, b: number, a: number?): Color

                declare udim2: {
                    fromScale: (x: number, y: number) -> UDim2,
                    fromOffset: (x: number, y: number) -> UDim2,
                } & ((xScale: number, xOffset: number, yScale: number, yOffset: number) -> UDim2)

                declare cframe: {
                    identity: CFrame,
                    angles: (pitch: number, yaw: number, roll: number) -> CFrame,
                    lookAt: (from: Vector3, to: Vector3) -> CFrame,
                } & ((x: number, y: number, z: number) -> CFrame)
                  & ((position: Vector3) -> CFrame)
                  & ((from: Vector3, to: Vector3) -> CFrame)

                declare task: {
                    wait: (seconds: number?) -> number,
                    spawn: (handler: () -> ()) -> number,
                    delay: (seconds: number, handler: () -> ()) -> number,
                    cancel: (handle: number) -> (),
                    every: (seconds: number, handler: () -> ()) -> { cancel: (self: any) -> () },
                    after: (seconds: number, handler: () -> ()) -> { cancel: (self: any) -> () },
                    debounce: <A...>(handler: (A...) -> (), seconds: number) -> (A...) -> (),
                    throttle: <A..., R...>(handler: (A...) -> R..., seconds: number) -> (A...) -> R...,
                }
                """);
        return out.toString();
    }

    private static String clazz(ClassDef<?> def) {
        StringBuilder out = new StringBuilder(256);
        out.append("declare class ").append(def.name())
                .append(" extends ").append(def.parent() == null ? "Instance" : def.parent().name())
                .append('\n');

        // the frame a place reads and writes without naming a property, from the same branch of
        // Proxies that serves them. they belong to whichever class introduces cframe, and the rest
        // inherit them
        PropertyDef frame = def.property("cframe");
        if (frame != null && frame.index() >= inherited(def)) {
            out.append("    position: Vector3\n");
            out.append("    rotation: Quat\n");
            out.append("    worldCframe: CFrame\n");
        }

        for (CallbackDef callback : def.callbacks()) {
            if (def.parent() != null && def.parent().callback(callback.name()) != null) continue;
            out.append("    ").append(callback.name()).append(": ((...any) -> ...any)?\n");
        }

        for (EventDef event : def.events()) {
            // every event carries the instance it happened to, so one shape covers all of them
            // a chat command also carries the line and its words, and a channel hands over the message
            String shape = def == Classes.CHAT_COMMAND ? "ChatCommandSignal"
                    : def == Classes.TEXT_CHANNEL ? "ChatMessageSignal" : "InstanceSignal";
            out.append("    ").append(event.name()).append(": ").append(shape).append("\n");
        }

        PropertyDef[] properties = def.properties();
        // a subclass keeps its parent's property indices, so everything past that count is its own
        // and everything before it is already declared on the class it extends
        for (int i = inherited(def); i < properties.length; i++) {
            out.append("    ").append(properties[i].name())
                    .append(": ").append(luau(properties[i])).append('\n');
        }
        out.append(verbs(def.name()));
        return out.append("end\n\n").toString();
    }

    // methods a single class carries. properties cannot drift because they come from the
    // registry; these are written by hand in two places and a test is what holds them together
    private static String verbs(String className) {
        return switch (className) {
            case "Camera" -> """
                        function shake(self, trauma: number): ()
                        function kick(self, pitch: number, yaw: number, roll: number, seconds: number): ()
                        function fovPunch(self, degrees: number, seconds: number): ()
                        function clearEffects(self): ()
                        function worldToScreen(self, world: Vector3): Vector3?
                        function screenToRay(self, x: number, y: number): (Vector3, Vector3)
                    """;
            case "Character" -> """
                        function distanceTo(self, other: Instance): number
                        function distanceSqTo(self, other: Instance): number
                        function canSee(self, other: Instance, range: number?): boolean
                        function isGrounded(self): boolean
                        function isInWater(self): boolean
                        function isMoving(self): boolean
                        function lookDirection(self): Vector3
                        function facing(self, other: Instance, maxAngle: number?): boolean
                        function walkTo(self, point: Vector3, options: PathOptions?): boolean
                        function follow(self, target: Instance, distance: number?): ()
                        function stopWalking(self): ()
                        function isWalking(self): boolean
                        function jump(self): ()
                        function lookAt(self, point: Vector3): ()
                        function face(self, direction: Vector3): ()
                    """;
            case "Part" -> """
                        function overlapping(self, options: QueryOptions?): { Instance }
                        function closestPoint(self, position: Vector3): Vector3
                        function contains(self, position: Vector3): boolean
                        function bounds(self): (CFrame, Vector3)
                        function worldBounds(self): (Vector3, Vector3)
                    """;
            case "Zone" -> """
                        function players(self): { Instance }
                        function occupants(self): { Instance }
                        function contains(self, position: Vector3): boolean
                    """;
            case "Sound" -> """
                        function play(self): ()
                        function stop(self): ()
                    """;
            default -> "";
        };
    }

    private static int inherited(ClassDef<?> def) {
        return def.parent() == null ? 0 : def.parent().properties().length;
    }

    // an enum declares the strings it accepts rather than "string", so an editor completes
    // them and a typo is red before the place is ever run
    private static String luau(PropertyDef property) {
        if (property.type() != PropertyType.ENUM) return luau(property.type());
        List<String> names = Enums.names(property.defaultValue().getClass());
        return names.stream().map(name -> '"' + name + '"')
                .collect(Collectors.joining(" | "));
    }

    private static String luau(PropertyType type) {
        return switch (type) {
            case BOOL -> "boolean";
            case INT, NUM -> "number";
            case STRING, ASSET, ENUM -> "string";
            case VEC3 -> "Vector3";
            case QUAT -> "Quat";
            case CFRAME -> "CFrame";
            case COLOR -> "Color";
            case UDIM2 -> "UDim2";
            case REF -> "Instance?";
        };
    }
}
