package com.meekdev.moud.script.types;

import com.meekdev.moud.core.clazz.ClassDef;
import com.meekdev.moud.core.clazz.ClassRegistry;
import com.meekdev.moud.core.clazz.PropertyDef;
import com.meekdev.moud.core.clazz.PropertyType;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

// the luau definitions a place is edited against, written from the class registry rather than kept
// beside it. a property that is not declared cannot appear here, so the api and what an editor
// believes about it cannot drift (8.7)
public final class Types {

    private static final String DIRECTORY = ".moud";
    private static final String FILE = "types.d.luau";

    private Types() {}

    public static Path write(Path place, ClassRegistry classes) throws IOException {
        Path directory = place.resolve(DIRECTORY);
        Files.createDirectories(directory);
        Path file = directory.resolve(FILE);
        Files.writeString(file, declare(classes));
        return file;
    }

    public static String declare(ClassRegistry classes) {
        StringBuilder out = new StringBuilder(4096);
        out.append("""
                -- generated by moud, do not edit and do not commit
                -- the classes below come from the class registry, so this file cannot describe a
                -- property that does not exist

                declare class Vector3
                    x: number
                    y: number
                    z: number
                    magnitude: number
                    unit: Vector3
                    function __add(self, other: Vector3): Vector3
                    function __sub(self, other: Vector3): Vector3
                    function __mul(self, scale: number): Vector3
                    function __unm(self): Vector3
                end

                declare class Color
                    r: number
                    g: number
                    b: number
                    a: number
                end

                declare class Quat
                    x: number
                    y: number
                    z: number
                    w: number
                end

                declare class CFrame
                    position: Vector3
                    rotation: Quat
                    lookVector: Vector3
                    rightVector: Vector3
                    upVector: Vector3
                    function __mul(self, other: CFrame): CFrame
                end

                declare class Connection
                    function disconnect(self): ()
                end

                declare class ChangedSignal
                    function connect(self, handler: (property: string) -> ()): Connection
                end

                declare class InstanceSignal
                    function connect(self, handler: (instance: Instance) -> ()): Connection
                end

                declare class StepSignal
                    function connect(self, handler: (delta: number) -> ()): Connection
                end

                declare class ReloadedSignal
                    function connect(self, handler: () -> ()): Connection
                end

                """);

        out.append("""
                declare class Instance
                    name: string
                    className: string
                    parent: Instance?
                    changed: ChangedSignal
                    childAdded: InstanceSignal
                    destroying: InstanceSignal
                    function add(self, className: string, properties: { [string]: any }?): Instance
                    function addAll(self, className: string, properties: { { [string]: any } }): number
                    function destroy(self): ()
                end

                """);

        for (ClassDef<?> def : classes.all()) {
            out.append(clazz(def));
        }

        out.append("""
                declare class Game
                    world: Instance
                    stepped: StepSignal
                    renderStepped: StepSignal
                    reloaded: ReloadedSignal
                    persist: { [string]: any }
                end

                declare game: Game

                declare function vec3(x: number, y: number, z: number): Vector3
                declare function color(r: number, g: number, b: number, a: number?): Color

                declare cframe: {
                    identity: CFrame,
                    angles: (pitch: number, yaw: number, roll: number) -> CFrame,
                    lookAt: (from: Vector3, to: Vector3) -> CFrame,
                } & ((x: number, y: number, z: number) -> CFrame)
                  & ((position: Vector3) -> CFrame)
                  & ((from: Vector3, to: Vector3) -> CFrame)

                declare task: {
                    wait: (seconds: number?) -> number,
                    spawn: (handler: () -> ()) -> number,
                    delay: (seconds: number, handler: () -> ()) -> number,
                    cancel: (handle: number) -> (),
                }
                """);
        return out.toString();
    }

    private static String clazz(ClassDef<?> def) {
        StringBuilder out = new StringBuilder(256);
        out.append("declare class ").append(def.name())
                .append(" extends ").append(def.parent() == null ? "Instance" : def.parent().name())
                .append('\n');

        // the frame a place reads and writes without naming a property, from the same branch of
        // Proxies that serves them. they belong to whichever class introduces cframe, and the rest
        // inherit them
        PropertyDef frame = def.property("cframe");
        if (frame != null && frame.index() >= inherited(def)) {
            out.append("    position: Vector3\n");
            out.append("    worldCframe: CFrame\n");
        }

        PropertyDef[] properties = def.properties();
        // a subclass keeps its parent's property indices, so everything past that count is its own
        // and everything before it is already declared on the class it extends
        for (int i = inherited(def); i < properties.length; i++) {
            out.append("    ").append(properties[i].name())
                    .append(": ").append(luau(properties[i].type())).append('\n');
        }
        return out.append("end\n\n").toString();
    }

    private static int inherited(ClassDef<?> def) {
        return def.parent() == null ? 0 : def.parent().properties().length;
    }

    private static String luau(PropertyType type) {
        return switch (type) {
            case BOOL -> "boolean";
            case INT, NUM -> "number";
            case STRING, ASSET, ENUM -> "string";
            case VEC3 -> "Vector3";
            case QUAT -> "Quat";
            case CFRAME -> "CFrame";
            case COLOR -> "Color";
            case REF -> "Instance?";
        };
    }
}
