package com.moud.net.protocol;


import java.util.List;
public sealed interface Message permits
        Hello,
        Ping,
        Pong,
        SceneList,
        SceneOpAck,
        SceneOpBatch,
        SceneCreate,
        SceneCreateAck,
        SceneDelete,
        SceneDeleteAck,
        SceneSelect,
        SceneSave,
        SceneSaveAck,
        SceneSnapshot,
        SceneSnapshotRequest,
        SchemaSnapshot,
        ServerHello,
        AssetManifestRequest,
        AssetManifestResponse,
        AssetUploadBegin,
        AssetUploadAck,
        AssetUploadChunk,
        AssetUploadComplete,
        AssetDownloadRequest,
        AssetDownloadBegin,
        AssetDownloadChunk,
        AssetDownloadComplete,
        AssetDeleteRequest,
        AssetDeleteAck,
        PlayerInput,
        RuntimeState,
        RequestRespawn,
        EditorModeChanged,
        ProjectInfoRequest,
        ProjectInfo,
        ProjectCreate,
        ProjectCreateAck,
        ScriptActionListRequest,
        ScriptActionListResponse,
        ScriptActionInvoke,
        ScriptActionInvokeAck,
        ScriptFileReadRequest,
        ScriptFileReadResponse,
        ScriptFileWriteRequest,
        ScriptFileWriteAck,
        EditorDiagnosticEvent,
        UiNodeEvent,
        MultiMeshData,
        MeshPublish,
        MeshGeneratorPublish,
        PlayerMotion,
        PlayerClientState,
        PlayReady,
        CursorState,
        CollisionGeometrySnapshot,
        ScriptMessage,
        AssetPathOp,
        AssetPathOpAck {
    MessageType type();
}
