{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.stephengold",
    "module": "jolt-jni-Linux64",
    "version": "3.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "jolt-jni-Linux64-3.5.0.jar",
          "url": "jolt-jni-Linux64-3.5.0.jar",
          "size": 742212,
          "sha512": "8747ad2e212f7527d6e29781a513e6c4e45a0247f4eba062b637e5e3d5383e7e8fa9c9121bc8751cbda99e36f50a94edddeda0067137bd56f5b78bdb5b1db55e",
          "sha256": "1cfe905ff92816a6b92bd3838bfec132bfa2424542e7e3aa4e5a00a7331b5656",
          "sha1": "0df713614f51cd6d22647a83add6629a5d04e23d",
          "md5": "eae8eb271e3e1d7478dd1c46cbf09cb1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jolt-jni-Linux64-3.5.0.jar",
          "url": "jolt-jni-Linux64-3.5.0.jar",
          "size": 742212,
          "sha512": "8747ad2e212f7527d6e29781a513e6c4e45a0247f4eba062b637e5e3d5383e7e8fa9c9121bc8751cbda99e36f50a94edddeda0067137bd56f5b78bdb5b1db55e",
          "sha256": "1cfe905ff92816a6b92bd3838bfec132bfa2424542e7e3aa4e5a00a7331b5656",
          "sha1": "0df713614f51cd6d22647a83add6629a5d04e23d",
          "md5": "eae8eb271e3e1d7478dd1c46cbf09cb1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jolt-jni-Linux64-3.5.0-javadoc.jar",
          "url": "jolt-jni-Linux64-3.5.0-javadoc.jar",
          "size": 2364066,
          "sha512": "a6c6610ca5204d2c600db5e1dd99bff611c70b87f58d8780c9799f04ddeb5fe972d8fbbc6a4b3622ca6af3fd10cc8d73946436dad796e1d6c72746c0f73ef8d4",
          "sha256": "0c00d495ffb642898597abfc4f5c19c0f3f9e308f65bc64f593b7875bacb20b1",
          "sha1": "dd9c99a30d43a14782f0f3df223267a3579c2996",
          "md5": "31a23d5407efeca9290fb8ff75823cab"
        }
      ]
    }
  ]
}
